extends "res://scripts/debug/verify_bank_finance.gd"
func _initialize() -> void:
	var run := RunState.new()
	run.initialize_cash_cents(0)
	check(run.create_studio_with_traits("Lease",&"action",[&"expensive_lease"]) and run.get_cash_cents()==580000,"Lease refund starts 5800")
	check(run.advance_calendar_cycle() and run.advance_calendar_cycle() and run.get_cash_cents()==528500,"First actual rent 515")
	var report := run.get_studio_finance_report()
	check(report.monthly_rent_cents==51500 and report.rows[0].rent_due_cents==51500 and run.get_studio_finance_snapshot().obligations.size()==1,"One rent bill and report category")
	var l := F.create(550000,51500)
	l=step(step(l),200000)
	l=step(step(l),200000)
	var q:=F.bank_quote(l,50000,12,&"lease")
	check(q.accepted and q.capacity_cents==37125,"Bank deducts actual 515 once")
	var hired:=F.hire_employee(l,F.hire_quote(l,&"lease"),&"lease")
	q=F.bank_quote(hired.ledger,50000,12,&"lease")
	check(q.accepted and q.capacity_cents==36875,"Bank subtracts payroll once beside actual rent")
	l=F.plan(l,4,l.cash_cents,-(l.cash_cents-50000),&"other_expense").ledger
	l=step(step(l))
	check(l.obligations[-1].paid_cents==50000 and l.obligations[-1].unpaid_cents==1500,"Partial single premium rent preserves original due")
	check(F.plan(l,7,0,0,&"calendar",0,0,true).is_empty(),"Rent arrears block productive action")
	var recovered:=F.plan(l,6,0,1500,&"other_income")
	check(not recovered.is_empty() and recovered.ledger.obligations[-1].unpaid_cents==0,"Genuine receipt recovers original bill")
	check(F.report(recovered.ledger,6,0).available and bytes_to_var(var_to_bytes(recovered.ledger))==recovered.ledger,"Lease finance reconstruction exact")
	print("Lease verification: %d checks, %d failures" % [checks,failures])
	quit(failures)
