from pathlib import Path
import json,hashlib,subprocess
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'design-logs/task20-v1'
s=json.loads((OUT/'summary.json').read_text()); results=json.loads((OUT/'verification.json').read_text())
assert all(x['exit']==0 and not x['errors'] for x in results)
assert all(hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==h for p,h in json.loads((OUT/'source-before.json').read_text()).items())
check=subprocess.run(['git','diff','--check'],cwd=ROOT,capture_output=True); assert check.returncode==0
(OUT/'diff-check.log').write_bytes(check.stdout+check.stderr)
text='''PATCH NOTES — TASK 20 EARLY / AFTER-GAME-4 PUBLISHER TIMING v1
COMPLETE bounded read-only comparison, 2026-09-29. Every Crown/Neon offer, target, cash cap and Promotion amount below remains an UNAPPROVED CANDIDATE, not playable gameplay.

Source and authority
Current main HEAD 608a2c62ab0850cf607f7ff627b042a49b5d2dfb plus verified local Task 21, tutorial, Studio and Feature-map changes. Saved branch/HEAD/status/diff and hashes before capture. Refreshed queue Task 20 after Task 19; read its full brief, cumulative §59/§61, Task 15 matched-draw log, Task 17 strong-route source/traces and actual Contract, RunState and ReleasedGameSales code. No production file changed during this task; no commit or push. Pending work and .codex-godot-temp preserved. Prior first-game SideStreet income is absent throughout this baseline.

Actual Godot eligibility and routes
Twelve native four-release captures: six baseline strong-policy cases and six paired Game-2 Marketing variants. Production seeds 270927000/270927097/270927194, paired environment/Contract seeds 290929000..290929005. Correlated, high-effort automated routes, not twelve independent policies or human playtests. All complete four games and two Game-5 Design hands without a cash/card-supply blocker.
Baseline Reviews by production seed: (6.4,9.8,8.9,8.9), (7.3,8.6,9.2,9.5), (5.9,9.3,9.7,9.6), each twice. Crown Review>=7 first qualifies at Game 1 in 2/6, Game 2 in 4/6. Baseline Neon eligibility is 0/6 through Game 4. Marketing variant: after six QA hands in Game-2 Beta, commit QA25/Marketing50/Insider25 for one normal productive cycle, then choose from visible cards for Marketing and four-card Marketing specialization. Additional-hands allowance was bounded at eight if needed; this cohort did not need them. Game-2 launch Awareness becomes 154/141/131 by seed, each twice; all 6/6 now genuinely meet >=125 at Game 2 with unchanged respective Reviews 9.8/8.6/9.3. Native actions and draws, known-Bug decisions, cash, calendar, Reviews and frozen markets are in routes_0.json / routes_1.json. These offers are eligibility predicates only: no live Crown/Neon Contract was accepted.

Ownership, affordability and persistence
Free IDs are the six current guaranteed starting Features, plus actually purchased starter roster. Reconstruct each later ownership state only from successful, cycle-stamped Store/reserve transactions; assert final reconstructed ownership equals actual RunState IDs. Earliest Crown pools: 15 Primitive Features for the two Game-1 unlocks, 27 for the other four. All after-Game-4 pools and all early/late Neon pools contain 27 Primitive Features. Recorded Sounds is bought and owned but excluded from these Primitive Contract pools. The four Core Passes are separate renewable supply. Pool growth is never inferred from cash or game number.
At final captured opportunity all ten remaining implemented Store nodes are individually affordable in each native route; they are unpurchased/unowned and never appear in the modeled Contract pools. Individual quotes do not prove simultaneous basket affordability or purchase intent. User reports about 90%/40%/all-affordable progression and 4.6/8.9 Reviews remain uncaptured human observations, not pass/fail targets. No prices, Review, supply or payouts were adjusted to match them.
The same proposed one-shot persistent offer is either accepted at first eligible Studio or held until after Game 4. No automatic card grant, expiry, regeneration or repeated payout is modeled. Neon focus is frozen at acceptance to the owned-pool's largest printed primary-Core total (stable Graphics/Sound/Technology/Design tie order): Design in all Neon pairs. Early and late use the same focus. Crown has no chosen focus.

Contract method and exact formulas
960 modeled Contracts: 2 publishers x 6 routes x 2 acceptance times x 2 visible-card policies x 20 paired draw seeds. Shadow seed = 200929000 + route_index*101 + trial_index. Python Random is explicitly a shadow PRNG, not Godot's RNG sequence. Every recorded random pair is then replayed through actual ContractPhase._draw_one; all 15,360 draws agree. All 1,920 hands are committed through isolated actual ContractState, with matching printed Scope, half-Core scores, specialization, finite exhaustion, valid changed priorities and two-hand completion. Isolated existing Ironclad result accounting is discarded; no shadow publisher cash enters RunState.
Seven candidates, choose four; one legal same-type redraw of the visibly weakest card per hand; finite Features reserved/exhausted, renewable Passes, old-definition exclusion. Studio supplies current bank 4. Each hand restores one capped redraw. After hand one, draw the next pool under old priorities, then commit 40/20/20/20 toward the weakest current Core (Crown) or frozen focus (Neon), costing one productive cycle and restoring one capped redraw; later redraw uses new weights. Exactly two hand cycles plus one changed-priority cycle. No Feature play fees. Acceptance/dismissal zero cycles/cash. All end at bank 4; subsequent Studio reconstruction uses existing refill.
Ordinary Contract policy maximizes 4*printed Scope + half-Core sum/2. Synergy policy chooses the best visible four for the lower-target completion objective, with printed Scope and specialization tiebreaks. Neither reads future cards. Identical final hands are rescored for both target variants; the target comparison never changes draws or selection policy. This ordinary Contract policy is a limited realistic-play sensitivity on the same high-effort production routes, not a complete ordinary human four-game simulation.
Crown required Scope S=9 or10, each Core target4: N=2*min(Scope,S)+sum min(H_i,8)+2*min_i(min(H_i,8)); D=2*S+48. Neon S=10 or11, focus target9, other Core target2: N=2*min(Scope,S)+3*min(H_focus,18)+sum_other min(H_i,4); D=2*S+66. H_i=2*resolved Core. Cash=floor(cap*N/D), caps192000/156000 cents; Promotion=floor(cap*N/D), caps12/20 whole points. No rounding before floors. A higher Scope target can increase a partial-completion fraction when added Scope raises both numerator and denominator while Core remains short; it is not uniformly a harsher payout rule.

Timing and exact-cent finance
2,786 native earned/settled sales snapshots match independent integer calculations before overlays. Keep each frozen release's Review, launch Awareness and market; insert three Contract cycles at the selected Studio checkpoint and shift subsequent recorded actions/releases by three. Fixed-action finance overlay, not a second native gameplay run. Pay modeled publisher cash exactly once at the final Contract hand. Track actual Store/reserve costs/cycles and cash before each next purchase; 0/1,920 target/timing evaluations encounter a new affordability failure. No compensation or negative live cash.
Bank whole Promotion once, consume it on the first subsequent successful launch only. Early Crown boosts Game 2 (2 routes) or Game 3 (4); early Neon boosts Game 3. After-Game-4 completion leaves Promotion banked for Game 5: this trace has no Game-5 launch, so no late Promotion sales benefit is invented. Pending older-title settlements remain separate sales and are never labeled publisher income.
monthly.json compares both arms at identical even run cycles; earned equals settled at these month boundaries. Raw native action snapshots retain intervening earned/unpaid differences. purchases.json records pre-purchase cash; outcomes.json separates direct payout and incremental Promotion revenue. Primary endpoint is the last common native-supported action cycle plus inserted cycles, floored to the last month boundary. Because early Contract cycles delay Game 4 while late acceptance follows its release, the primary endpoint still contains different Month-1 settlement progress. An additional +24-cycle no-new-action accrual projection is explicitly modeled, not a legal wait action, and is used to expose that horizon effect. It does not claim Game 5 sales or spending.

Results (120 draws per row/time; currency means in dollars)
'''
for k,g in s['groups'].items():
 e,l=g['early'],g['after_game4']; short=g['early_minus_late_final_cash']; long=g['early_minus_late_after24_projection']
 text+=f"{k}: early payout ${e['mean_payout']/100:.2f}, Promo {e['mean_promotion']:.2f}, full {e['full']}/120; late ${l['mean_payout']/100:.2f}, Promo {l['mean_promotion']:.2f}, full {l['full']}/120. Early Promo revenue ${e['mean_promotion_revenue']/100:.2f}. Median early-minus-late cash ${short['median']/100:.2f} at primary endpoint; ${long['median']/100:.2f} after +24 projected cycles (range ${long['min']/100:.2f}..${long['max']/100:.2f}).\n"
text+='''
Interpretation and recommendations
Waiting brings no Primitive-pool gain for Neon or the four Game-2 Crown unlocks. All their paired draws/payouts match exactly when ownership matches; waiting merely relocates three cycles, publisher liquidity and next-launch Promotion. Crown's two Game-1 unlocks can grow from15 to27 owned Primitive Features, but the reward improvement is small and policy-dependent. The synergy lower-target mean rises only about $7.27 across the six Crown routes; ordinary mean falls about $22.06. Bigger ownership does not guarantee better weighted candidates.
At the primary endpoint late acceptance has more settled cash, despite early Promotion earning extra sales. This is a launch/settlement timing comparison, not evidence that delaying always dominates. After +24 projected cycles the median reverses: lower-target synergy early advantages are about $643 Crown / $1,171 Neon; Crown still has negative individual pairs. Late Promotion remains a future asset, unvalued because there is no captured Game-5 launch. Do not use this truncated result to lock an optimal acceptance time.
RETAIN persistent non-expiring one-shot timing as the structural option, with transparent next-launch Promotion and a frozen acceptance pool. DEFER cash/Promotion caps: high-effort routes and current provisional long-tail sales magnify Awareness, while ordinary Contract completion is materially lower. REVISE the target comparison specification before any numerical approval: raising the Scope target also increases its relative weighting and can increase partial payout; choose whether that behavior is intended. Retain 9/4 and10/9 only as the shortlist, not approved values. Need a human recorded purchase/production/Marketing sequence and an actual fifth launch to value held Promotion against earlier cash. No employee, trait, publisher, era Feature or balance implementation was made.

Verification and reproducibility
Godot4.7.1, fresh isolated APPDATA/LOCALAPPDATA per command (normal host profile is unreliable). Editor import, native shadow-draw/hand replay, balanced Primitive Contract, SideStreet Contract, Scope/year, sales earning/settlement, and lifespan verifiers passed. git diff --check and unchanged scripts/scenes/data hash guard passed. Godot may print the host root-certificate-store warning on exit; no parse/script/assertion failures. Native mouse/keyboard execution is unavailable; all route actions are headless through actual phase APIs, not visible UI human play.
From patch-notes, use the bundled Python executable with -B:
  analysis/task20_batch_v1.py
  analysis/task20_compare_v1.py
  analysis/task20_verify_v1.py
  analysis/task20_report_v1.py
Exact Godot argument vectors, profile directories, exit codes and scanned errors are in verification.json and *.command.json; individual logs sit beside them. Native capture command: Godot --headless --path <patch-notes> --script res://analysis/task20_routes_v1.gd -- --mode=exact --count=6 --arm=next_game --neon=0 (then --neon=1). Replay: --script res://analysis/task20_native_rules_v1.gd. Import: --editor --import. Focused: --script res://scripts/debug/verify_<name>.gd.
Added analysis files: task20_routes_v1.gd(+UID), task20_batch_v1.py, task20_compare_v1.py, task20_native_rules_v1.gd(+UID), task20_verify_v1.py, task20_report_v1.py. Evidence directory: patch-notes/design-logs/task20-v1/ (routes, contract_traces, outcomes, purchases, monthly, eligibility, summary, source hashes/status/diff and commands). This standalone TXT is copied to local New Data Logs and uploaded separately; raw/source remain local. All work remains uncommitted/unpushed.
'''
name='Task20_Early_vs_Game4_Publisher_Timing_v1.txt'
(OUT/name).write_text(text,encoding='utf-8')
dest=Path('C:/Users/64jus/Downloads/Patch Notes Design Folder/New Data Logs')/name; dest.write_text(text,encoding='utf-8')
(OUT/'artifact-hashes.json').write_text(json.dumps({str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in list((ROOT/'analysis').glob('task20_*'))+list(OUT.glob('*.json')) if p.is_file()},indent=2),encoding='utf-8')
print(str(dest)); print('Verified report and source guard.')
