"""Versioned Task32 findings, data receipt and source guard."""
from pathlib import Path
import csv,gzip,hashlib,json,shutil
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'design-logs/task32-v1'
DEST=Path('C:/Users/64jus/Downloads/Patch Notes Design Folder/New Data Logs');B=DEST/'Task32 Contracts Rent Rebaseline v1';B.mkdir(exist_ok=True)
s=json.loads((OUT/'summary.json').read_text());gate=json.loads((OUT/'focused-gate.json').read_text());commands=json.loads((OUT/'commands.json').read_text())
assert gate['passed'] and not s['source_changed'] and not commands['changed'] and all(r['exit']==0 and not r['errors'] for r in commands['results'])
text='''PATCH NOTES — TASK32 CONTRACTS ON RENT / RETAINED POOLS v1
STATUS: COMPLETE as a bounded READ-ONLY comparison. No gameplay, values, canonical authority, loans, traits, payroll or publisher implementation changed. Recommendations remain candidates.
SOURCE: main e054791d0348d90faf70e9d827892c351fa018bc plus verified local Task33 typed credit and preserved retained-three/four-replacement work. Runtime hash manifest unchanged throughout. Task29 is committed. Task33 and this analysis are local/uncommitted; cached origin/main matches HEAD; independent remote check failed because git remote-https helper is unavailable. No commit/push. No AGENTS.md found; no overlapping local implementation. .codex-godot-temp preserved.
SOURCES: live Task32 refreshed after Task33 completion/readback, authority §§59/61/64–69, Task23 fixed-share report, Task29 finance/Task30 lending logs, native ContractState/phase, RunState, StudioFinanceLedger and ReleasedGameSales. Historical pre-rent cash traces were not used as this baseline.

DECLARATION / METHODS
36 current native routes: Action automatic roster, seeds1104/4417, ordinary/synergy visible policies;12/18 first-game budgets; no-Contract versus available Ironclad/eligible SideStreet; two calendar alignments. Alternate alignment is an actual one-cycle Design priority change, not a Wait. Later games use18-cycle budgets. Horizon5 releases or actual block, <=120 productive actions/180seconds per route;2workers/1200second native batch limit. Four separately labeled Neon-directed arms change G2 priorities after2 QA hands and use visible Marketing choices for4 hands, including specialization; this adds1 productive cycle. No fabricated cash/cards/Review/launch or campaigns. Complete source/seed/action/draw/redraw traces retained.
Additional targeted strong probe replays previously observed Action/synergy4417 with legal Recorded Sounds purchase: genuine G2 Review9.0 atcycle32, launchAwareness107, cash0 and rent arrears$147.65. Subsequent SideStreet first hand cannot commit. Crown would unlock on that immutable Review but zero-advance first hand cannot resolve this cash block. No fallback funding invented. Human8.7/Scope29/14-development-cycle screenshot is contextual only: no corresponding provenance-complete human capture found in local New Data Logs or normal Patch Notes user capture location. It is not synthesized.
32 normal control routes plus4 directed Marketing routes yield127 releases; strong probe adds2 separately. All20 available-Contract routes reach5 releases. Among16 no-Contract controls,1 reaches5,7 stop after2 and8 after1. These are blocks under the declared policy; an unused real Ironclad offer may still be an alternative. They are not proof the whole game is unrecoverable or human progression ceilings.
Native first-release and later scores/Scope/Awareness, actual costs, lowest cash, rent/arrears, cycles and first blocked action are in native-summary.csv and raw traces. Native-common-calendar.csv contains234 matched even-cycle checkpoints. All-title earned/settled cash and publisher receipt/rent attribution reconcile separately.

CURRENT ELIGIBILITY / CANDIDATE SCORING
Real Ironclad pays40000c once on acceptance plus its native completion remainder. SideStreet requires Ironclad completion and each qualifying immutable release's printed Scope>=required30. All first titles remain below30; no first-title SideStreet is granted. Crown condition is immutableReview>=7; Neon condition is committed launchAwareness>=125, not campaigns or older-title Awareness. Directed Marketing routes actually reach129 (seed1104) and127 (4417) on G2; their Reviews6.9/6.5 do not get overwritten. Crown7+ is reached naturally on later native routes; sampled 9.0 is a separate cash-constrained route.
640 modeled Contracts on four representative current-source timelines: Crown ordinary/alignment0 and synergy/alignment1; Neon synergy at both alignments. Early actual unlock versus afterG4, ordinary/synergy Contract choices,20 seeds200929000..019, two hands alone versus two hands plus changed priority. Frozen owned Primitive pool18 in all matched cases; later Store classes excluded, Passes renewable, Features finite, retain3/refill4, same-type redraws and productive redraw replenishment. Neon focus explicitly freezes Graphics before draw from highest owned printed-primary total (display-order ties). No future information enters hand choice.
Native verification reproduces8320 draws and1280 committed hands across640 candidates, including scoring/exhaustion.1280 exact target evaluations use Task23 fixed shares, not the older target-dependent denominator:
Crown S9/10: [18*min(Scope/S,1)+sum min(H_i,8)+2*min_i min(H_i,8)]/66.
Neon S10/11: [20*min(Scope/S,1)+54*min(H_focus/18,1)+sum_other min(H_i,4)]/86.
H=2*Core score. Fractions exact; cash=floor(cap_cents*fraction), Promotion=floor(cap_points*fraction), independently. Zero/full endpoints and stricter-target monotonicity pass. Caps192000c/12 and156000c/20 are trial anchors only. No Crown/Neon offer exists in runtime.

FINANCE / PROMOTION
604 deduplicated timelines include36 exact native baselines plus full reward, cash-only and delay-only overlays. Every overlay uses native StudioFinanceLedger._apply with actual direct-action affordability, older-title settlement, rent service, financial block and credit, and native ReleasedGameSales. Full journal is reconstructed/validated by public report at each timeline end; all36 baselines match native final cash/cycle and each title's units/earned/settled exactly. No discrepancies. This avoids repeated whole-history validation at every observation; an initial slower run was interrupted, and a public-plan benchmark matches. It does not change runtime code.
Insert speculative hands immediately after the chosen successful release and before existing later actions. No advance; reward commits only on hand2. Changed priority is a third genuine productive-cycle opportunity. Frozen subsequent player choices/profiles/markets remain unchanged; these are fixed-action finance overlays, not interactive new offers. No future income funds an earlier action.
Two hands cross one50000c rent due. Three cycles cross one or two dues (50000/100000c), depending on alignment. Receipts table separates publisher cash, prior-title sales settling during those actions and rent actually paid. No prior settlement is counted as a publisher reward.
Promotion is keyed to unique modeled offer, banked only on successful completion, consumed once at the next successful launch; old frozen titles unchanged. Cash-only isolates incremental Promotion units/earned/settled at common calendar cycles. All1280 target arms and their cash/delay controls remain financially legal on the four representative paths. This is not true of every possible studio state, as the9.0 probe demonstrates. Game5 late Promotion is launched but its later income is not observed at the endpoint. Conditional24-cycle title-only projections are separately labeled, assume no later releases/campaigns, grant no spendable cash and are not free Wait actions.
PAIRS
Cash-only early-minus-late is negative: Crown-$62.94..-$34.97; Neon-$90.90..-$48.95. Promotion changes the observed timing ranking. Narrow predeclared cap2 diagnostic atseed200929000/synergy/threecycles: Crown early becomes$27.97 behind late; Neon ties. This is a sensitivity, not a recommendation to reduce caps.
Two sequential modeled offer orders at truly eligible G4 (Crown→Neon and Neon→Crown,2hands each) both end$16431.59 with identical summed Promotion; payment timing differs. Four cycles pay$1000 rent. Unique offer IDs each commit once, pending Promotion adds then consumes once on G5. Offers are serialized; no simultaneous Contract or stacking cap is implemented. Existing native repeated-callback/payout guards pass maintained Contract regressions. Future integrated chooser/Persistence/Promotion rollback still needs implementation acceptance tests.

SELECTED DISTRIBUTIONS
GROUPS
The extra priority cycle sometimes improves the payout, but may cross another$500 bill; it is not automatically profitable. All early/late claims here are paired within the same captured production route; the representative Crown production policy and alignment are not a broad independent policy-frequency study. Target9/10 often ties because actual Scope exceeds both; monotonicity still holds.

RECOMMENDATION — FOR REVIEW, NOT LOCKED
Retain the fixed-share formulas and shortlist Crown Scope9/fourCore4 with$1920+12Promotion, NeonScope10/focus9/otherCore2 with$1560+20Promotion for the next design review. Do not add larger historical27/48 caps without new evidence. Use a visible frozen Neon focus chooser, pending-offer list, exactly-one-active state and an upcoming-rent warning for priority changes. Preserve one-shot guarantees and distinguish cash completion from delayed Promotion. Current evidence supports making early acceptance available, not forcing it: cap sensitivity reverses the ranking, and cash-constrained eligible studios may be unable to start zero-advance work.
Minimum implementation acceptance: immutable unlock/release IDs and Scope gate; frozen owned-only pool; two finite/renewable hands and retention; priority/redraw cost; exact floors including zero reward; payment-once and no simultaneous offers; failed transaction/launch preserves cash, cards, RNG and banked Promotion; next launch consumes once; no earlier title mutation; both rent alignments; reconstruction and future save identity; chooser/Back/focus UI. Starwave, loyalty, reputation and broader publisher mechanics remain deferred. No compensation or economy retune is proposed from a single route.

VERIFICATION / ARTIFACTS
Godot4.7.1: all36 native routes and strong probe exit0 with no script/parse markers;640-contract native replay passes;604 native accounting overlays and6 narrow sensitivities pass. Focused Primitive Contract, SideStreet, Scope/year, finance ledger/integration, typed credit and earning/settlement suites pass; Task33's preceding full59-suite/import gate remains the unchanged runtime baseline. git diff --check0 and source hash guard unchanged. Known root-certificate/artwork warnings retained. No new graphical UI, exported interactive smoke or durable-save claim.
Commands: python -B analysis/task32_batch_v1.py; python -B analysis/task32_prepare_v1.py; Godot --headless --path <project> --script res://analysis/task32_native_rules_v1.gd; same task32_overlay_v1.gd and task32_sensitivity_v1.gd; python -B analysis/task32_analyze_v1.py; python -B analysis/task32_report_v1.py. Exact absolute command/profile/result files included. Native routes complete in declared batch budget; analysis runs bounded separately. Pilot corrected enum priority keys and deferred the alignment action until the old Studio scene exited; pilot errors are not gameplay validation passes.
Changed files: analysis/task32_batch_v1.py, task32_routes_v1.gd, task32_strong_probe_v1.gd, task32_prepare_v1.py, task32_native_rules_v1.gd, task32_overlay_v1.gd, task32_overlay_benchmark_v1.gd, task32_sensitivity_v1.gd, task32_analyze_v1.py, task32_report_v1.py and Godot UID companions. No runtime changes. Logs/data in design-logs/task32-v1; portable New Data Logs/Task32 Contracts Rent Rebaseline v1. Exact inputs, actions, native snapshots, monthly tables, credit/rent rows and conditional title projections retained; large JSON compressed in portable bundle.
BLOCKERS/LIMITS: no human8.7 trace; strong9.0 route stops with genuine arrears; old unrelated Alpha-exit guard remains open; modeled offers/Persistence are not gameplay; remote verification helper missing; exported interactive smoke remains blocked and was not forced. No blocker to this bounded comparison. Next dispatched task:31, refresh authority/archive before selection UI.
'''
text=text.replace('PAIRS',str(s['pair_summary']))
text=text.replace('GROUPS','\n'.join(f'{k}: {v}' for k,v in s['groups'].items() if "'early'" in k and (k.endswith('2, 9)') or k.endswith('2, 10)') or k.endswith('3, 9)') or k.endswith('3, 10)'))))
log=DEST/'Patch Notes - Task32 Contracts Rent Rebaseline v1.txt';log.write_text(text,encoding='utf-8')
for p in OUT.rglob('*'):
    if not p.is_file():continue
    target=B/p.relative_to(OUT);target.parent.mkdir(parents=True,exist_ok=True)
    if p.suffix=='.json' and p.stat().st_size>500000:target.with_suffix('.json.gz').write_bytes(gzip.compress(p.read_bytes(),mtime=0))
    else:shutil.copy2(p,target)
for p in (ROOT/'analysis').glob('task32*'):shutil.copy2(p,B/p.name)
shutil.copy2(log,B/log.name)
print(log)
