"""Publish the bounded evidence as local TXT/Markdown, without balance edits."""
from pathlib import Path
import csv, hashlib, json, subprocess
from task17_analyze_v1 import load, OUT, ROOT, projection
LOGS=Path(r'C:\Users\64jus\Downloads\Patch Notes Design Folder\New Data Logs')
def money(c): return f'${int(c)/100:,.2f}'
def table(headers,rows):
    return '\n'.join([' | '.join(headers), ' | '.join(['---']*len(headers))]+[' | '.join(map(str,r)) for r in rows])
def main():
    r=load('strong_next_game.json')['rows'][0]; audit=load('analysis_summary.json')
    profiles={p['id']:p for p in load('native_sales_projections.json')['profiles']}
    summary=list(csv.DictReader((OUT/'sales_trial_summary.csv').open()))
    s=[x for x in summary if x['profile']=='strong_final.json/0/game_2' and x['carry_bp']=='1500' and x['price_cents']=='10000']
    reviews=load('strong_final.json')['rows']
    lines=['PATCH NOTES — TUTORIAL REPAIR AND TASK 17 LEGAL STRONG-RELEASE FINDINGS v1',
    'Date: 2026-09-29. COMPLETE bounded implementation verification and read-only analysis. Numerical lifespan, campaign and fan gain/loss values remain UNAPPROVED TRIALS. No fan system or proposed balance rule was implemented.',
    '', 'SOURCE, AUTHORITY AND WORKTREE',
    'Local main HEAD and origin/main tracking ref: 608a2c62ab0850cf607f7ff627b042a49b5d2dfb. This task did not fetch, commit or push. The repair is still uncommitted. Initial status/diff and SHA256 source manifest are archived. Twelve tracked files were already modified when this task began; all were preserved byte-for-byte. Existing untracked analysis and .codex-godot-temp were preserved. No applicable AGENTS.md was found in the repository or inspected ancestors.',
    'Refreshed sources: current Task 17 in https://docs.google.com/document/d/1n6o5g8Gj_sDTs5Ku6PLM37OWPPyLpDM_ASfNiD9MRkY/edit ; cumulative authority https://drive.google.com/file/d/1kmlzNwRbckS9OxucMd5WPYNOF2Dx6QT1/view (modified 2026-09-28T07:29:01.983Z, especially section 60); Game Lifespan and Campaign Handoff https://docs.google.com/document/d/1T2ot5EOg5meZpPhyCI1zpb7Mgvs6-Q15WEVzrGW_IGM/edit ; Task 9 findings https://drive.google.com/file/d/1awRDS6m4bERiTttnAlBqaptEvChvfiou/view and final task9_fixed raw traces; Task 15 findings https://drive.google.com/file/d/1lRzFtKug3AXCMzh9z5RMmOYWYb8BqgLR/view and synergy-first capture harness. Earlier instructions in the handoff to pause repository checking were superseded by this explicit user request. Current source is the baseline, not old uncommitted/push claims in historical logs.',
    '', 'REPRODUCTION AND TUTORIAL REPAIR',
    'A git archive of 608a2c6 was extracted into an isolated temporary directory. Godot import logged the undefined _get_first_game_tutorial() parse errors despite returning exit 0; the committed tutorial verifier exited 1. The pushed verifier also references get_first_game_guidance(), absent from that revision. Logs record the errors verbatim. An initial archive invocation used the wrong nested project path and exited 1 before import; that setup error is retained separately and is not the defect reproduction.',
    'The requested repair was already in the current uncommitted worktree: design_phase.gd defines both methods; gameplay_hud.gd consumes contextual guidance; phase_workspace.gd displays the current instruction above the backlog and its detailed hover text; contextual_tip.gd resets dismissal for each new tutorial step; verify_first_game_scripted_tutorial.gd covers presentation and actions. I inspected and retained these changes rather than overwrite them. Existing first_game_tutorial.gd supplies the two seeded legal pools and the narrow guaranteed Pass redraw.',
    'First pool: highest initial priority chooses four matching primary Core cards, with tied maxima randomly resolved. The tip explains four-card Specialization, x1.5 Core gains, unchanged Scope, cash cost and one productive cycle. Second pool: three matching cards in a different Core; select ONE nonmatching card and Redraw, consuming one normal allowance and zero cash/cycles. The replacement is a legal matching renewable Pass. Players may ignore both suggestions, change priorities, or redraw differently; normal affordability, finite Feature exhaustion, renewal, familiarity and cycle rules remain. No hidden free cash, time or redraw refill was added by the tutorial repair.',
    'Fresh headless import and all 43 verify_*.gd suites passed with no SCRIPT ERROR/Parse Error/FAIL markers. Tutorial: 0 failures across 80 seeded deal routes, plus real scene flow, UI guidance, ignored lessons, overflow/affordability rollback, selection and reconstruction checks. Design, Alpha, Beta, gameplay/HUD, shared redraw, Store, Contract, sales/calendar and exact-cent suites all passed. The import return code alone was deliberately not treated as proof. Existing root-certificate and missing-art warnings remain; no cross-platform case cleanup was attempted. A prior rendered 1152x648 lesson screenshot was visually inspected and agrees with the unchanged guidance code. Native mouse/keyboard play and fresh graphical capture were not performed.',
    '', 'LOW-REVIEW CALIBRATION',
    'Six fresh historical-policy routes (two each cautious/ordinary/optimizer) reused Task 9 production seeds, rosters and action budgets on this worktree. First-game Review changed 0.9→0.5 cautious, 2.5/2.4→1.9/1.8 ordinary, 3.4/3.2→2.7/2.5 optimizer. Game-2 Reviews remained 0.8, 1.9–2.0 and 2.3–2.5 respectively. Awareness and release cycles match; reduced first-game revenue changes later cash and sometimes Store/campaign affordability. The first tutorial deals changed and those legacy policies do not follow the tutorial, so lower scores here do not imply broken Review arithmetic. Full paired values are in low_review_calibration.csv. No 48-arm rerun was needed.',
    '', 'LEGAL HIGH-REVIEW ROUTE AND LIMITS',
    'Six accepted two-game cases use three production seeds, each with two independently seeded environment/Contract streams; these are not six independent production seeds. All six Game-2 Reviews are >=7; four are >=9. Two smoke cases and an intermediate six-case harness run were exploratory and excluded from this final denominator (three intermediate cases captured only Game 1). Five matched four-release opportunity routes plus a three-arm repeat-campaign cohort and one exact replay are additional correlated executions, not independent players.',
    'Starting point was Task 15 synergy/Genre-aware legal scene control. The bounded search added visible Scope/weak-Core prioritization, more production, twelve QA-heavy Beta hands using only Known Bug counts for decisions, and legal reserve purchases funded by release sales and Contracts. First game uses 8 Design / 10 Alpha / 12 Beta hands. Later games use 22 / 24 / 12. This is an intentionally long existence proof, not an efficient or recommended human strategy. Contract and market inputs are ordinary uniform seeded RNG rolls; Review RNG is seeded and sampled normally. No chosen favorable Review, cash, market outcome, card definition, or draw was injected. Initial Contract uniform rolls enter before its first deal; no replacement of a published pool is used in accepted strong routes. Later redraws use current Godot chance. Hidden Bugs are recorded as telemetry but never queried by the new selection policy.',
    'Canonical replay: production seed 270927000; environment/Contract stream seed 290929000. Per project Design deal/finalization seeds +1/+2, Alpha +3/+4, Beta deal/Insight +5/+6, Review +7. Game 2 production seed 271427000; Game 3 271927000; Game 4 272427000. Initial snapshot uniform rolls and all Contract initial rolls are in the trace. Later matched opportunity markets have an independent title/case seed, keeping outcomes matched when an arm takes extra actions. Generated release IDs alone are normalized for replay comparisons.',
    'Starter purchases: '+', '.join(r['starter_roster'])+'. The six guaranteed Features come from RunState. Total initial owned Scope is 20, within the 23 cap; purchase spending stays within $4,000. First selected hand: sound_pass, 8_bit_music, sound_pass, 8_bit_sound (Sound Specialization). Second lesson redraws controller in slot 1 (zero-based) to graphics_pass, then commits text, graphics_pass, sprites, 4_color_palette (Graphics Specialization). All actual cost/cycle changes are recorded.',
    'After Game 1, Ironclad pays '+money(r['ironclad']['completion']['payout_cents'])+' total; first SideStreet pays '+money(r['sidestreet_1']['completion']['payout_cents'])+'. Buy the quoted later upgrade/reserve and then affordable unowned Primitive reserves in ID order, keeping at least $1,800 before each added reserve purchase. These later purchases each consume one productive cycle and allow existing sales to earn/settle. The resulting Game-2 eligible supply reaches 41 printed Scope including Recorded Sounds. No supply or cash is manufactured.',
    table(['Release','Genre','Scope','Core G/S/T/D','Bugs remaining','Review','Awareness','Launch cycle','Cash at launch','Month-1 units'],[(i,r[f'game_{i}']['genre'],r[f'game_{i}']['scope'],'/'.join(map(str,r[f'game_{i}']['cores'])),r[f'game_{i}']['hidden_bugs']+r[f'game_{i}']['known_bugs'],r[f'game_{i}']['final_review'],r[f'game_{i}']['awareness'],r[f'game_{i}']['cycle'],money(r[f'game_{i}']['cash_cents']),r[f'game_{i}']['month_1_units']) for i in range(1,5)]),
    'Game 2: production 10.0, full Scope, Bug multiplier 1.0, sampled variance +0.25 (roll 76), pre-Genre clamp 10.0, Genre Fit 0.9811501, rounded Review 9.8. Frozen launch market 9,000 bp; Awareness 111. This is compatible with the user’s human 9+ report, but not a reconstruction of their 4.7→9.2 route. The full first-game production standard is reachable with the small pool; its 20/30 Scope holds Review down. Later full ownership plus renewable Passes removes that restriction. Do not mistake an automated short-hand policy for a progression ceiling.',
    '', '24-MONTH SALES AND CAMPAIGNS',
    'Current Godot ReleasedGameSales.create/next_cycle generated 132 pure sales arms from 22 captured profiles (16 strong-route/repeated profiles and six weak Game-2 releases). Every arm follows 49 half-months: 24 release-age months plus one extra boundary step for odd launch alignments. An independent exact-integer model matches all '+str(audit['native_snapshot_parity'])+' snapshots. The actual no-campaign gameplay continuation also matches '+str(audit['live_sales_snapshot_parity'])+' captured sales snapshots. The 1,188 carryover/price/schedule arms are labeled sensitivity projections, not live UI purchases or independent seeds.',
    'Trial formula: Month-2 organic scaled Awareness = launch Awareness×5000 + 200×carryover_bp; Month-3+ = floor(previous_scaled×(2500+55×Review_tenths)/10000). Active Awareness adds floor(100000/(prior_campaigns+1)) for the campaigned age month only. Units=floor(500×Review_tenths×active_scaled×market_bp/(70×200×10000×10000)). Net cents=floor(cumulative units×999×70/100); two half-month earning slices; only even run cycles settle. Month 1 uses its captured launch projection. No fan input, payroll or bill is counted.',
    table(['Game-2 schedule at $100','24-month units','Earned net','Fees','Incremental net after fees'],[(x['schedule'],x['units_24'],money(x['earned_24']),money(x['cost_cents']),money(x['direct_margin_cents'])) for x in s]),
    'For Game 2 the first, second and third marginal campaign returns are +$116.78, +$11.89 and −$23.08. A repeat campaign is sometimes profitable, but an every-month loop loses $1,467.84 over 24 months. The title still sells at month 24; in the actual continuation it becomes dormant later and a first campaign at age month 33 revives 31 units, net +$116.78. Units never feed back into decay; campaign boosts do not reset organic Awareness.',
    'Weak ordinary Review 2.0: 305 units and $2,132.86 net over 24 months without campaign, first zero-unit month 6. First $100 campaign adds eight units and loses $44.06; a delayed first campaign at dormancy also revives eight units and loses $44.06. Every-month campaigns lose $2,160.14. Prices $50/$75/$100 and carryover 0/15/30% are all in sales_trial_summary.csv; these remain unapproved candidates. Per-title projection cash starts at captured release cash and includes only that title’s future settlements and campaign fees, not other titles or development spending. For actual run cash use actual_calendar_boundaries.csv, which includes all live costs and overlapping sales.',
    '', 'MONTHLY GAME-2 TABLE: CURRENT 15%, NO CAMPAIGN',
    'The run cash column is from the actual legal no-campaign continuation; earned/settled figures belong only to Game 2. Other titles and Store/Feature costs explain differences from single-title revenue.',
    ]
    p=profiles['strong_next_game.json/0/game_2']; projected=projection(p,'none')
    cycles={int(x['cycle']):x for x in r['live_cycles']}
    lines.append(table(['Age month','Calendar cycle','Units this month','Organic Awareness','Cumulative net earned','Settled','Actual run cash'],[(x['age_month'],x['cycle'],x['monthly_units'],f"{x['organic_awareness_scaled']/10000:.4f}" if x['age_month']>1 else 'launch',money(x['entitlement_cents']),money(x['settled_cents']),money(cycles[x['cycle']]['cash_cents'])) for x in projected[:48] if x['age_cycle']%2==0]))
    lines += ['', 'MATCHED OPPORTUNITY AND SETTLEMENT',
    'At run cycle 172 all five arms share $24,952.30, identical releases and ownership. Game 3 has just earned Month 1; Game 2 is dormant. Each campaign is bought through the Studio summary button. Store uses its real button, Contract uses actual hand selection, and next-game uses Pre-Development plus real hands. No free waiting cycles are simulated in these live branches.',
    table(['Arm','Game-4 launch cycle','Game-4 Review','Cash at Game-4 launch','Difference from next game'],[(x['arm'],x['game4_cycle'],x['game4_review'],money(x['game4_cash']),money(x['cash_delta_at_release'])) for x in audit['opportunities']]),
    'A campaign delays Game 4 by one cycle; the full Contract arm uses two hands plus one changed-priority cycle and delays it by three. Its first hand is also logged separately: it earns sales, but the $975 reward arrives only on hand two. The Store arm buys permanent ownership and improves Game-4 Review by 0.1; its near-term cash loss is not a lifetime valuation of that card. Different launch cycles are not a claim of equal-time cash profit.',
    'At calendar cycle 232, immediate-next-game has already settled $3,363.63 of Game-4 sales. Both campaign arms only launch Game 4 at cycle 232, so its first sales earning/settlement is delayed. Subsequent legal Game-5 Pre-Development and two Design hands capture these boundaries. This liquidity cost can be much larger than a ~$120 direct campaign margin; delayed sales are not automatically lost revenue. Previously earned older-title settlement is never credited as campaign profit.',
    'A second, separately matched three-arm cohort first buys a legal Game-2 campaign at age month 3, then compares no campaign, a first campaign on the newer Game 3, and a repeat on dormant Game 2 at shared cycle 174. Both are affordable; the newer first campaign adds $130.77 after fee, while the older repeat adds only $4.90. Both delay Game 4 one cycle. This favors first promotion of a newer hit over repeating an old hit at current trial values, not over starting development when near-term liquidity matters.',
    '', 'RECOMMENDATIONS — NONE LOCKED',
    'Carryover: DEFER numerical lock. Retain 15% as the control; 0/30% change the passive tail substantially but do not generally rescue weak campaign economics. Compare against human release-age retention expectations before tuning.',
    'Review-sensitive retention: RETAIN direction, DEFER coefficients. Current strong titles persist far longer than weak ones and zero-unit revival works. Very long development remains cheap because payroll/bills are unavailable, so these tails cannot calibrate future finance.',
    'Campaign price: REVISE the decision presentation before considering a global price cut. $100 loses on weak releases but can profit on hits; $50/$75 make repeats more attractive. Show expected incremental units/net separately from pending settlement.',
    'Fixed boost: RETAIN as a bounded trial control. It makes campaign value depend on frozen Review/market; validate player expectations with a real strong-release trace.',
    'Diminishing repeat: RETAIN for now. Second campaign may narrowly profit; third is negative in the canonical route and every-month spending loses. No unlimited profitable same-title repeat loop was found in the bounded 24-month sweep.',
    'Timing and one-campaign-per-age-month: RETAIN as tested boundaries, DEFER UX lock. Eligibility is narrow and the cycle can delay a new release’s settlement. A tooltip should distinguish release age from calendar month. No timing alternative was implemented.',
    'Fan gain/loss rates: DEFER entirely. They are unapproved trial candidates; no fan counter or numerical rate was added, inferred from these sales, or written into the canonical authority.',
    '', 'LIMITATIONS, FILES AND NEXT TASK',
    'No implementation blocker remains for the local tutorial repair or bounded Task 17 analysis. The repair is NOT pushed. Native graphical input remains unverified. No durable save/load reconstruction is claimed: replay starts a fresh run with recorded seeds/actions. Long-run priority/Pass economics and lack of payroll make the high-Review existence route an upper-effort policy, not representative novice behavior. Original Task-9 policy uses hidden QA telemetry and fixed historical outcome hooks; it is retained only as matched historical calibration, separately from the new visible-information strong policy.',
    'The accepted strong route uses only current playable systems; Crown/Neon/Starwave unlocks do not create unavailable offers. No employee, fanbase, bills, traits, proposed Feature effects, publisher Promotion or balance tuning was implemented. The earlier human 4.7→9.2 and later ~9 observations remain separate evidence. Ask a human to record purchase/Genre choices, lesson comprehension, hand counts, redraw decisions, Review breakdown, cash before/after settlement and whether campaign payoff feels worth the delayed next game.',
    'Existing tutorial repair files retained: scripts/phases/design_phase.gd; scripts/ui/gameplay_hud.gd; scripts/ui/phase_workspace.gd; scripts/ui/contextual_tip.gd; scripts/debug/verify_first_game_scripted_tutorial.gd. Existing seven Studio refill/owned-price edits preserved. Newly added analysis: analysis/tutorial_task17_verify_v1.py; analysis/task17_strong_route_v1.gd; analysis/task17_sales_projection_v1.gd; analysis/task17_analyze_v1.py; analysis/task17_report_v1.py. Godot creates companion .uid files for the new GDScripts. Evidence directory: design-logs/tutorial-task17-v1/. New Data Logs TXT has this report’s title. No gameplay source changed during this verification/analysis turn.',
    'Commands and outcomes are in verification.json, reproduction-corrected.json, *_commands.json and *.command.json, with corresponding full .log files. Fresh final import, source-preservation hashes and git diff --check are in final_checks.json. The source ZIP includes the exact worktree code and reusable base harnesses, avoiding dependence on the broken pushed commit. Set APPDATA and LOCALAPPDATA to separate empty temporary directories before Godot; this host’s normal profile can crash before the engine banner. Run from patch-notes: python -B analysis/tutorial_task17_verify_v1.py; Godot --headless --path . --script res://analysis/task17_strong_route_v1.gd -- --count=6 --tag=final; repeat with --count=1 --arm=next_game|campaign_new|campaign_old|store|contract --tag=<arm>; use --repeat-prelude=1 and --tag=repeat_<arm> for the three repeat arms; replay next_game with --tag=replay; run res://analysis/task17_sales_projection_v1.gd; python -B analysis/task17_analyze_v1.py; python -B analysis/task17_report_v1.py. Calibration commands and all absolute executable paths are archived.',
    'Task 17 can be marked COMPLETE with these findings. The exact next eligible task is Task 18 — Test curated Production redraws in legal play (read-only); it was not started here.',
    ]
    report='\n\n'.join(lines)+'\n'
    (OUT/'Findings_v1.md').write_text(report,encoding='utf-8')
    LOGS.mkdir(exist_ok=True)
    (LOGS/'Tutorial_Repair_and_Task17_Strong_Release_Findings_v1.txt').write_text(report,encoding='utf-8')
    action_lines=['# Canonical four-release action trace v1','Seed 270927000; environment/Contract stream 290929000. Exact draws, redraw slots and states: strong_next_game.json. Prices/cycles remain current gameplay.']
    for x in r['starter_purchases']: action_lines.append(f"Starter buy {x['id']}: {money(x['price_cents'])}; cash {money(x['after']['cash_cents'])}.")
    for i,a in enumerate(r['actions'],1):
        before=a.get('before',{}); after=a.get('after',{})
        text=f"{i}. {a['phase']} / {a.get('game',a.get('id',''))}"
        if 'cycle' in before: text+=f": cycle {before['cycle']}→{after['cycle']}, cash {money(before['cash_cents'])}→{money(after['cash_cents'])}"
        if 'draw' in a: text+='; draw '+', '.join(a['draw'])
        if a.get('redraws'): text+='; redraw '+json.dumps(a['redraws'])
        if 'selected' in a: text+='; play '+', '.join(a['selected'])+'; '+a.get('synergy','')
        if 'cores' in after: text+='; Core '+str(after['cores'])+' Scope '+str(after['scope'])
        if 'rolls' in a: text+='; uniform snapshot rolls '+str(a['rolls'])
        action_lines.append(text)
    (OUT/'Replay_Actions_v1.md').write_text('\n\n'.join(action_lines),encoding='utf-8')
    print('Report and replay written')
if __name__=='__main__': main()
