from pathlib import Path
import json,hashlib,subprocess
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'design-logs/task18-v1'
s=json.loads((OUT/'summary.json').read_text())
assert all(hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==h for p,h in json.loads((OUT/'source-before.json').read_text()).items())
assert all(r['exit']==0 and not r['errors'] for r in json.loads((OUT/'verification.json').read_text()))
p=subprocess.run(['git','diff','--check'],cwd=ROOT,capture_output=True); assert p.returncode==0
(OUT/'diff-check.log').write_bytes(p.stdout+p.stderr)
text=f'''PATCH NOTES — TASK 18 CURATED PRODUCTION REDRAW TRIAL v1
Status: COMPLETE bounded read-only comparison, 2026-09-29. No reward or numerical value approved.

Source and authority
HEAD main 608a2c62ab0850cf607f7ff627b042a49b5d2dfb plus verified local Task 21 and pending tutorial/Studio/Feature-map edits. Refreshed current task queue before starting, read Task 18, cumulative authority including section 61, Task 16 findings and 96 historical normal-arm traces, current production/redraw/first-tutorial/RunState code. Task 21 removes under-required-Scope SideStreet offers. No production source changed during this analysis; SHA256 source guard and git diff --check pass. No commit, push or canonical authority write.

Method and reproducibility
72 complete two-game scene routes: 12 cases x ordinary and synergy/Genre-aware policies x normal, curated same-class, and choose-Core upper-bound arms. Twelve of these continue through Game 3 (two per policy/arm). Cases share six production seeds 270927000 + floor(index/2)*97 and 12 environment streams 290929000+index; repeated arms are not independent samples. Separate second-option stream 180929000+index. A further one-case protocol probe passes. Starting rosters are legal 20–23 Scope under the $4,000 cap. Ordinary plays 4 Design/6 Alpha/6 QA-heavy Beta hands; synergy plays 6/8/6. Tutorial opening specialization and guaranteed redraw are retained, so these short policies are separate from Task 17's high-effort route and from human observations.
Ordinary values visible Scope/Core, with the existing Sound preference; synergy uses public Genre ratios and specialization. Both make affordable four-card choices, use real Godot candidate supply, exhaustion, action and Review code, and never query hidden Bugs for QA decisions. The trial is considered on the first post-training redraw with three matching visible primaries or in Alpha, once per project. It is chosen before seeing the second offer. No hypothetical hire/payroll cost is charged in playable routes.
Current Godot's ordinary planner supplies the first replacement from its 50/50 class split and priority weights. The second distinct definition is drawn from that same legal class without replacement on the separate stream. Exact inverse-weight intervals pass the chosen card back through the existing atomic redraw commit; the ordinary phase stream consumes exactly its one normal roll. Market, Contract and Review streams are not consumed by the additional offer. The stronger upper bound chooses the most frequent printed primary Core in the visible pool, then a weighted legal definition in that Core; it is explicitly not the candidate rule. Visible Feature exclusion, finite exhaustion and immediate same-ID ban are retained; renewable Pass duplicates remain legal, matching current source. No all-card visible exclusion was invented.
2,196 successful replacement events pass independent legality, one-bank charge, zero-cycle/cash and selected-slot checks. Each arm is compared to its no-perk state/roll/first-offer prefix until the first changed replacement. Thereafter different finite supply and hands are a consequence of the trial; they are not identical checkpoints. Counterfactual first/second/choice and exact eligible class are saved per decision. 4,230 common-calendar cash/settlement comparisons avoid conflating launch time with common-cycle money.
The harness exposes no player cancellation UI. Its protocol probe checks invalid replacement rejection and canceled pre-confirmation availability reads: no options are revealed to the policy, no cash/bank/perk/pool/random-state mutation occurs. The automatically chosen option and normal charge then commit together via Godot. An eventual interactive implementation must keep cancellation before hidden options are revealed or provide a separately approved sealed-choice protocol; this report does not approve a free peek/reroll interface. Existing multi-slot selected-order and rollback tests also pass.

Findings
Curated ordinary: 26/26 projects use the perk; 25 uses give no immediate evaluated-hand gain, only one chooses the second card. Game 2 Review delta median 0, range -0.1..0.0; one route worsens. Cash at Game 2 launch delta median 0, range $0..+$11.19. One route changes later selected hands. Four eligible scarce-class decisions fall back to ordinary and retain the use. Curated synergy: 26/26 uses, 20 without immediate gain, six second-card choices across two changed-hand routes. Game 2 Review delta median 0, one improvement +0.5, none lower. Launch cash median delta 0, one -$40 cost difference; no shortage blocks a route. Game 1 and the small Game 3 cohort have no Review gain in this arm. No unused-perk project in these deliberately early-use policies; normal controls never spend the perk. These counts distinguish no-use, used-but-no-gain and fewer-than-two fallbacks.
The Core upper bound also has median zero Game 2 Review gain. Ordinary range -0.3..+0.1 (two worse, one better), launch-cash range -$470.49..+$104.89. Synergy has two improvements up to +0.3 and no worse Review. It is not uniformly superior, and does not justify silently strengthening the candidate.
Sound specialization does not consistently grow: ordinary normal/curated both have 16 Sound hands; synergy normal has 48, curated 47. Curated synergy instead raises Design specialization 46->47. Pass-only hands ordinary 65->65, synergy 144->143. This small, correlated, Sound-preferring screen cannot establish a global dominant strategy. No live affordability/card-supply blocker occurs in these 72 paths. All released-game sales use the current playable trial coefficients, not locked lifespan balance.
At common cycles, curated cash differences range -$174.82..+$81.19 ordinary and -$110..+$442.52 synergy; timing and eventual settlement matter. These are observed extrema, not permanent income or salary capacity. Exact common-cycle values are in common_cycles.csv; launch comparisons above are separately labeled.

Historical denominator check
Reconstructed the 96 Task 16 normal-arm routes using current ledger primaries and actual successful Store/reserve ownership at each first Alpha pool. The 121 trained first-Alpha denominator reproduces. Counting any primary with exactly three visible cards yields 71/121, with 43 having an off-screen owned Alpha Feature of that primary legal. The queue's 68/121 and 37 do not reproduce under this explicit definition; retain them as an unverified historical screen, not current results. Fresh no-perk Task 18 routes (including small Game 3 cohort) have 52 trained first Alpha pools, 28 with a three-primary pattern, 23 with an off-screen matching Feature. These populations and definitions must not be pooled.

Hypothetical hire/payroll sensitivity — not playable expenses
1,728 fixed-action overlays: hire at run start or after Game 1; fees $0/$100/$200; salary $50/$75/$100 monthly; first due next crossed boundary or one further boundary later. No free hiring cycle was simulated as gameplay; hire cost/timing only is the stated shadow. Check both pre-action affordability and post-boundary cash, recording the first shortfall without mutating RunState or calling negative cash playable. {s['payroll_first_failures']} overlays hit a hypothetical shortfall. Each row records when cumulative salary/fee first exceeds the paired observed benefit; frequently this is the first due boundary because measured gain is zero. Even a later positive ending balance does not erase an earlier unaffordable action. hypothetical_payroll.json contains exact cents and boundary/phase. No new loan, bills, course or staff rule is implied.

Recommendation
REVISE/DEFER reward approval. Same-class choice is legally implementable through existing redraw machinery, but 45/52 uses have no immediate benefit under these policies and no median Review/cash gain. Keep the ordinary redraw alternative and scripted tutorial intact. Before considering implementation, test a deliberate hold-for-value decision policy and player comprehension of class choice; do not price an employee from the largest common-cycle windfall. DEFER the stronger Core option and all salary/hire/course values. Only the printed matching Pass+Feature successful Design training trigger remains locked.

Files and commands
Added analysis/task18_build_harness_v1.py, task18_curated_trial_v1.gd (+UID), task18_batch_v1.py, task18_analyze_v1.py, task18_report_v1.py. Outputs: design-logs/task18-v1/ six main raw JSON files; summary.json; common_cycles.csv/json; hypothetical_payroll.json; isolated-profile command JSON/logs; initial status/diff/source hashes and protocol trace. No gameplay files changed.
From patch-notes: python -B analysis/task18_build_harness_v1.py; python -B analysis/task18_batch_v1.py; python -B analysis/task18_analyze_v1.py; python -B analysis/task18_report_v1.py.
Godot 4.7.1: --headless --path <patch-notes> --script res://analysis/task18_curated_trial_v1.gd -- --policy=<ordinary|synergy> --reward=<normal|curated|core> --count=12 --game3-count=2. Protocol: --policy=synergy --reward=curated --count=1 --tag=_protocol --protocol-probes=1. Exact absolute executables and fresh APPDATA/LOCALAPPDATA profiles are in *.command.json.
Import, six focused suites (atomic selected redraw, class parity, shared redraw/priority, scripted tutorial, SideStreet Scope/year, lifespan trial), protocol probe and source-preservation checks all pass; git diff --check passes. Task 21's full 44-suite gate is preserved. No human graphical input was exercised. Current human approximately 4.6/8.9 observations and earlier >9 later-game reports are separate from these short automated policies.
Next eligible task: 19, trait/96-month-loan read-only rebaseline. Task 20 remains independently READY after Task 21. Evidence files remain local; only this standalone findings log is uploaded unless source/raw-payload upload is separately authorized.
'''
path=Path(r'C:\Users\64jus\Downloads\Patch Notes Design Folder\New Data Logs\Task18_Curated_Production_Redraw_Findings_v1.txt')
path.write_text(text,encoding='utf-8'); (OUT/path.name).write_text(text,encoding='utf-8')
print(path)
