from pathlib import Path
import json,hashlib,subprocess
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'design-logs/task19-v1'
s=json.loads((OUT/'summary.json').read_text())
assert all(hashlib.sha256((ROOT/p).read_bytes()).hexdigest()==h for p,h in json.loads((OUT/'source-before.json').read_text()).items())
assert all(r['exit']==0 and not r['errors'] for r in json.loads((OUT/'verification.json').read_text()))
p=subprocess.run(['git','diff','--check'],cwd=ROOT,capture_output=True); assert p.returncode==0
(OUT/'diff-check.log').write_bytes(p.stdout+p.stderr)
text='''PATCH NOTES — TASK 19 STRONG-ROUTE TRAITS AND FULL LOAN TERM v1
COMPLETE read-only rebaseline, 2026-09-29. All point/cash/benefit/penalty values remain UNAPPROVED CANDIDATES.

Source
Main HEAD 608a2c62ab0850cf607f7ff627b042a49b5d2dfb plus verified local Task 21, tutorial, Studio and Feature map changes. Inspected current branch/status/diff and saved source hashes before capture; no gameplay file changed, no commit/push. Refreshed queue Task 19 after Task 18 completion; read cumulative authority, Studio_Trait_Post_Integration_Recheck_v1 and Tutorial_Repair_and_Task17_Strong_Release_Findings_v1, prior candidate point/trait analyzers, live calendar/sales/Store source. Exactly-one manually selected background, separate optional Genre specialty, and 96 monthly loan dues are preserved structure. No trait UI, effect, staff, payroll or fan system was implemented.

Current native baseline
Six recaptured Task 17 high-effort two-release routes, same production seeds 270927000/270927097/270927194 and environment/Contract streams 290929000..290929005. All six remain legal with the unavailable Game-1 SideStreet omitted; all same purchases remain affordable. First and second Reviews: 6.4/9.8 twice, 7.3/8.6 twice, 5.9/9.3 twice. Game 2 launches three cycles earlier and with exactly $1,100/$975/$1,150/$1,200/$1,050/$1,150 less cash respectively, matching each historical omitted payout. No under-Scope cash farming, free grants or compensating balance edits. Qualified later releases retain SideStreet; owned versus merely affordable cards are not conflated.
One exact four-release continuation reaches cycle 231, including two legal Game-5 Design hands; another paired continuation uses the existing legal Game-3 campaign and reaches cycle 232. The no-campaign route releases at cycles 31/105/167/228 with Reviews 6.4/9.8/8.9/8.9. Thus cycle 192 and every loan due boundary are actual native productive cycles, not a clock skip. A fresh short-policy low control (2.9/5.7, from Task 18) and the earlier Task 3 ordinary policy recaptured on current source (1.9/2.0) are separate controls. The latter retains historical verification-controlled market/draw inputs and its older QA policy can inspect hidden Bugs; it is a historical-policy sensitivity, not a human or visible-only policy result. Current tutorial deals and absent SideStreet can change its old choices. Six high routes are only three production seeds with paired environment streams, not a population estimate.
1,360 native sales snapshots exactly match independent integer earned-entitlement and settled-cash calculations before trait overlays. Frozen per-release market basis points come from actual release records. Campaign history is replayed per release age. Earned and settled deltas are separate. Neutral outcomes equal native cash; no negative cash is introduced into Godot.

Trial scope and method
54 bounded scenarios x 10 route records = 540 fixed-action overlays, with monthly CSV, first pre-action affordability failures, boundary failures and launch/checkpoint JSON. No action adapts to hypothetical extra cash. The primary background arms are mutually exclusive Family +$300, Cult +200 fixed shadow fans (+60 Awareness under the old curve), or Publisher +15% first Ironclad reward. Specialty +10 is separate; it represents a matching-Genre choice, not a second background. Positive trait point opportunity costs use candidate $50 per point: Buzz +10 Awareness at one point, Resourceful first successful Store purchase $100 relief at one point, Lean 10% Feature-play relief capped $100 per project at two points. Unknown Name compares +2-point/$100 refund for -15 Awareness on all releases or -10 only on Game 1. No live fan gain/loss or attrition is implied by Cult.
Student Loan: +1/+2 point cash refunds at $50 per point; dues $5/$10/$15, exactly 96, beginning at cycle 2 (the next monthly boundary from studio creation). Candidate budgets 4/6 points, conversion $0/$50/$100 per unused point, with $300 cap or an uncapped sensitivity, include +1/+2 loan refunds. These are labeled conversion-only upper bounds, not approved builds or an enumeration of every trait combination. Extra starting cash does not bypass the existing $4,000 starter purchase or 23-Scope caps. A separate hypothetical $75 bill plus $100 monthly salary after Game 1 is not counted in no-staff play.

Six strong-route mean cash change at post-Game-2 Contract checkpoint
Family +$300: +$300. Resourceful: +$50 after its point opportunity cost. Lean: +$94.67 (range +$89..+$99). Buzz: +$551.40; separate matching specialty: +$601.40. Unknown -15/all: -$795.10 (all six negative); Unknown -10/first: -$253.15 (all six negative). Cult fixed +200-fan shadow: +$3,586.25; this large value depends on unimplemented fan conversion/persistence and strong sales, not an approved reward.
Publisher external funding +15%: +$297.49 mean; within-budget bound caps the additional reward at $2,400 minus actual Ironclad payout, mean +$293.40. A full-budget base payout would leave zero within-budget headroom; the external arm requires extra authorized funds. No actual Ironclad payout is altered. These bounds must not be merged into an asserted payable bonus.
Loan +2-point refunds at $5/$10/$15 dues: -$170/-$440/-$710 at the two-game endpoint (54 dues); +1-point refunds are another $50 lower. All primary no-staff loan and trait routes remain affordable in this cohort. Hypothetical bill/salary paths fail preflight in all six strong paths; the long no-campaign path's first shortfall is cycle 69 Alpha, $365.22. A later recovered balance cannot make a failed fixed action legal.

Full 96-dues evidence (one legal long route)
Paid-month checkpoints are cycles 8/24/48/192. Calendar month labels at those points are 5/13/25/97: month 1 starts at cycle 0, so paid month and calendar month are deliberately distinguished. Both conventions are recorded in checkpoints.json.
                         4 dues      12 dues      24 dues       96 dues
Native cash             $1,580.00   $1,160.00    $5,048.83     $29,763.48
+2 points, $5/month     $1,660.00   $1,200.00    $5,028.83     $29,383.48
+2 points, $10/month    $1,640.00   $1,140.00    $4,908.83     $28,903.48
+2 points, $15/month    $1,620.00   $1,080.00    $4,788.83     $28,423.48
Total dues exactly $480/$960/$1,440. The +1-point variants end another $50 lower. No 97th due is charged at later captured cycles. None of these loan-only paths misses a payment. First unaffordable obligations under other shadows are diagnostic; no repayment/default behavior is invented.

Campaigns, cash conversion and balance interpretation
The long campaign arm uses the existing $100 one-cycle campaign on Game 3, with frozen per-release awareness/market and concurrent older sales. It is a native trial campaign; all trait changes to those same earned/settled records remain external shadows. Monthly CSV includes both arms and costs, without labeling pending old revenue as campaign or Publisher income.
Unspent-point conversion grants $0..$600 in the tested neutral upper bounds; uncapped +2 refund can increase that to $800. Those cash differences are immediate before any sales, while a loan's later cost can far exceed its early refund. A $300 cap often makes an extra negative-trait point refund worth no additional starting cash. Unknown Name does not show the old early profitable cash ranking in these strong routes, but its $100 refund is still liquid before release and the lost revenue arrives later. Neither observation authorizes a cap, points price, penalty or exploit fix. A conversion-only neutral choice can dominate purchasing a low-value positive trait; settle whether unspent points convert at all before pricing positives.
The strong-route Buzz/Cult cash values greatly exceed earlier Task 3 weak-route rankings. This is a genuine horizon/Review sensitivity, not evidence to rebalance Review to match the user's approximately 4.6/8.9 observations. Human observations remain uncaptured action evidence; this small deterministic cohort is not a player ceiling or expected earnings forecast.

Disposition and unresolved rulings
RETAIN structural exactly-one background and separate specialty; retain exact 96-dues term. REVISE/DEFER all numerical trait prices. Family is the clearest bounded immediate effect to discuss; Resourceful/Lean need usage and timing explained. DEFER Buzz and especially Cult valuation until fan/carryover interactions are settled. DEFER Publisher Connections until funding and $2,400 cap treatment are explicit. Loan requires a missed/unaﬀordable payment ruling (reject action, debt, grace, or another consequence); this trial chooses none. Point budgets, conversion/caps, allowable positive/negative combinations, Cult attrition and bonus funding remain design decisions. Do not implement from cash rankings alone.

Verification and files
Added analysis/task19_routes_v1.gd and task19_low_control_v1.gd (+UIDs), task19_batch_v1.py, task19_analyze_v1.py, task19_report_v1.py. No production source changed. design-logs/task19-v1/ contains raw short/long/campaign/historical-policy traces, 54 scenario definitions, 540 outcomes, monthly.csv/json, checkpoints.json, summary, source hashes, initial status/diff, exact command JSON/logs. Raw files remain local; this standalone TXT is the Drive deliverable.
Commands from patch-notes: python -B analysis/task19_batch_v1.py; python -B analysis/task19_analyze_v1.py; python -B analysis/task19_report_v1.py. Extra captures: Godot --headless --path <patch-notes> --script res://analysis/task19_routes_v1.gd -- --mode=exact --count=1 --arm=campaign_new --tag=campaign; Godot --headless --path <patch-notes> --script res://analysis/task19_low_control_v1.gd. Binary is Godot_v4.7.1-stable_win64_console.exe, using fresh isolated APPDATA/LOCALAPPDATA; exact absolute commands are archived.
Editor import, four focused lifespan/sales/Scope-year/first-Studio suites, all route captures, 1,360 neutral parity checks, source SHA guard and git diff --check pass. Task 21's full 44-suite baseline remains unchanged. No graphical human playtest was performed. No blocker to the bounded analysis; next eligible task is Task 20, early Crown/Neon vs Game 4 timing under this new baseline.
'''
dest=Path(r'C:\Users\64jus\Downloads\Patch Notes Design Folder\New Data Logs\Task19_Strong_Route_Traits_and_96_Month_Loan_v1.txt')
dest.write_text(text,encoding='utf-8'); (OUT/dest.name).write_text(text,encoding='utf-8'); print(dest)
