"""Narrow coordinated completion reconciliation; preserve unrelated queue text."""
from pathlib import Path
R=Path(__file__).resolve().parents[4];D=R/'docs/codex'
p=D/'TODO.md';s=p.read_text(encoding='utf-8')
old='**Current user scope, 2026-10-08:** work on Fanbase tasks only; hold the other TODO work. The approved v2 Fanbase capture is complete below. Further Fanbase integration/tuning and the gated Cult review need their own resolved scope; no additional gameplay work is dispatched here.'
new='**Current user scope, 2026-10-08:** execute all feasible queued read-only studies and approved implementations; the earlier Fanbase-only hold is superseded. Preserve explicit design rulings and serial acceptance gates. [Current execution log](logs/2026-10-08-queue-completion-v1.md).'
assert old in s or new in s;s=s.replace(old,new,1)
s=s.replace('**Feature Pools Handoff 004 — QUEUED READ-ONLY, 2026-10-08; research-queue pacing comparison.**','**Feature Pools Handoff 004 — COMPLETE bounded READ-ONLY, 2026-10-08.** [80-route findings and43,635 independent checks](findings/research-pacing-v1/README.md). Early down payments and FIFO sequencing materially affect pressure; no new price/duration approval. Original scope:',1)
s=s.replace('**Feature Store first-node design review — READY for review, no implementation approval; updated 2026-10-06.**','**Feature Store first-node design review — COMPLETE review; candidate terms DEFERRED, 2026-10-08.** [Review and explicit deferral](threads/feature-store/REVIEW-v12-first-node-deferral.md). No candidate implementation or numerical approval.',1)
s=s.replace('**Contracts Starwave overnight design queue — READY READ-ONLY, 2026-10-08.**','**Contracts Starwave overnight design queue — COMPLETE bounded READ-ONLY, 2026-10-08.** [SW1](threads/contracts/FINDINGS-v11-starwave-foundation-cards.md), [SW2](threads/contracts/FINDINGS-v12-starwave-earned-rewards.md), [SW3 proposed pilot](threads/contracts/FINDINGS-v13-starwave-proposal.md). One legal foundation,12 modeled card arms,25 economic arms/60 candidates,87,279 independent checks. Numerical ruling remains OPEN. Original scope:',1)
s=s.replace('**Starwave overnight SW1–SW3 — READY READ-ONLY; user authorized queueing 2026-10-08.**','**Starwave overnight SW1–SW3 — COMPLETE bounded READ-ONLY, 2026-10-08; proposal awaits user ruling.** [SW1](threads/contracts/FINDINGS-v11-starwave-foundation-cards.md), [SW2](threads/contracts/FINDINGS-v12-starwave-earned-rewards.md), [SW3](threads/contracts/FINDINGS-v13-starwave-proposal.md). Low-cash advance rescue remains untested; no eligible SideStreet alternative at the legal foundation. Original scope:',1)
s=s.replace('**Task13 — BLOCKED on integration prerequisites; stale source dependency text reconciled.**','**Task13 — PARTIAL implementation, 2026-10-08; final release acceptance remains gated.** Startup validation/recovery/local diagnostics implemented;10 actual cold-start missing/malformed-file cases preserve valid Studio bytes through repair/Retry/Continue. One-command release gate added. [Execution and evidence](logs/2026-10-08-queue-completion-v1.md).',1)
# Keep original detailed C4 acceptance text as history, preceded by current outcome.
needle='**Contracts Crown/Neon bounded pilot — APPROVED ACTIVE/TRIAL design; C1–C3 implemented locally, C4 PARTIAL presentation; C5 exported extension open, reconciled 2026-10-08.**'
if needle in s:s=s.replace(needle,'**Contracts Crown/Neon bounded pilot — APPROVED ACTIVE/TRIAL; C1–C4 COMPLETE locally, C5 exported extension open, 2026-10-08.** Browser states corrected and verified with16 supported-size captures plus focused suites; [current log](logs/2026-10-08-queue-completion-v1.md). Original detailed acceptance follows.',1)
s=s.replace('C1–C3 COMPLETE locally, C4 PARTIAL browser presentation, C5 exported extension OPEN','C1–C4 COMPLETE locally, C5 exported extension OPEN')
s=s.replace('C4 browser presentation is PARTIAL and C5 exported interaction remains open','C4 browser presentation is COMPLETE locally and C5 exported interaction remains open')
s=s.replace("Starwave's three-hand/reward study is queued READ-ONLY","Starwave's bounded three-hand/reward study is COMPLETE READ-ONLY")
p.write_text(s,encoding='utf-8')
p=D/'threads/contracts/HANDOFF.md';s=p.read_text(encoding='utf-8');s+='\n## Execution reconciliation — 2026-10-08\n\nThe overnight SW1–SW3 read-only queue is complete: [SW1](FINDINGS-v11-starwave-foundation-cards.md), [SW2](FINDINGS-v12-starwave-earned-rewards.md), [SW3 proposed terms and precise future acceptance](FINDINGS-v13-starwave-proposal.md). All Starwave terms remain proposed/OPEN; no implementation is queued without a user ruling. C4 browser correction is complete locally with supported-size captures and focused checks in the [execution log](../../logs/2026-10-08-queue-completion-v1.md). C5 remains in Task10/11 acceptance. Earlier queued/partial C4 and SW1–SW3 rows above are historical.\n';p.write_text(s,encoding='utf-8')
p=D/'threads/contracts/README.md';s=p.read_text(encoding='utf-8');s=s.replace('# Contracts design thread','# Contracts design thread\n\nLatest execution2026-10-08: [SW1 foundation/cards](FINDINGS-v11-starwave-foundation-cards.md), [SW2 earned rewards](FINDINGS-v12-starwave-earned-rewards.md), [SW3 proposed pilot](FINDINGS-v13-starwave-proposal.md). Read-only queue complete; numerical ruling OPEN. C4 browser copy complete locally; C5 exported acceptance still tracked separately. See updated [HANDOFF](HANDOFF.md).',1);p.write_text(s,encoding='utf-8')
p=D/'CURRENT_STATE.md';s=p.read_text(encoding='utf-8');s=s.replace('## Playable loop','## Current queue execution\n\n2026-10-08: User expanded scope to all feasible TODO work, superseding the Fanbase-only hold. C4 publisher availability copy and Task13 startup data recovery are implemented locally; research pacing80 routes and Starwave SW1–SW3 bounded studies are complete. Proposals remain unapproved. Checkpoint/export acceptance continues; [dated execution log](logs/2026-10-08-queue-completion-v1.md) preserves exact checks and remaining gates.\n\n## Playable loop',1);p.write_text(s,encoding='utf-8')
print('Updated current scope and completed queue items; preserved remaining gates')

