"""Exact-cent fixed-action overlays. Sales inputs are regenerated by native Godot.

The bill and credit rules mirror outstanding_expenses.gd. No payroll producer
exists in gameplay; payroll order/timing below are explicit counterfactuals.
"""
from pathlib import Path
from collections import Counter, defaultdict
import json, gzip, itertools, hashlib, statistics, sys

HERE = Path(__file__).resolve().parent
ROOT = Path(r'C:\Users\64jus\Downloads\Patch Notes Design Folder\employees-comparison-20261006')
PENALTIES = {'rent':[5,10,20], 'payroll':[5,10,15]}
WAGES = [10,50,75,100]

def due_after(hire, first):
    cycle = int(hire['cycle'])
    if first == 'full': return cycle + (2 if cycle % 2 == 0 else 3)
    return cycle if hire['productive'] and cycle > 0 and cycle % 2 == 0 else cycle + (2-cycle%2)

def course_due(course, when):
    # Match the native ledger's expense-month convention. Passive enrollment
    # after an even boundary belongs to the new current month; productive
    # completion at that boundary belongs to the month just closed.
    c=int(course['cycle'])
    month=(c-1)//2+1 if course['productive'] else c//2+1
    return 2*(month+(1 if when=='next' else 0))

def bill(kind,cycle,cents,source):
    return dict(kind=kind,due=cycle,total=cents,paid=0,unpaid=cents,late=False,settled=-1,source=source,payments=[])

def service(b,cash,cycle):
    payment = min(cash,b['unpaid'])
    if payment:
        b['paid'] += payment; b['unpaid'] -= payment
        b['payments'].append(dict(cycle=cycle,cents=payment))
    if b['unpaid'] == 0: b['settled'] = cycle
    if b['unpaid'] or cycle > b['due']: b['late'] = True
    return cash-payment,payment

def close_credit(score,bills,cycle,profit):
    oldest = {}
    for b in bills:
        if not b['late'] or (not b['unpaid'] and b['settled'] <= cycle-2): continue
        age = (cycle if b['unpaid'] else min(cycle,b['settled']))-b['due']
        oldest[b['kind']] = max(oldest.get(b['kind'],-1),age)
    change = -sum(PENALTIES[k][min(age//2,2)] for k,age in oldest.items()) if oldest else (3 if profit>0 else 0)
    return max(300,min(850,score+change)),change

def replay(timeline,scenario,detail=False):
    cash = int(timeline['initial']); low = cash; cycle = 0; native_action_cycle=0; score = 600
    bills=[]; rows={}; releases=[]; stop=None; first_shortfall=None; checkpoints={}; store=False; hires={}; courses={}; credit=[]
    totals=Counter()
    due_rule = scenario['first']
    def row_for(month):
        return rows.setdefault(month,dict(month=month,earned=0,settled=0,direct=0,operating_direct=0,rent_due=0,payroll_due=0,rent_paid=0,payroll_paid=0,profit=0))
    def snap():
        return dict(cash=cash,native_action_cycle=native_action_cycle,rent_arrears=sum(b['unpaid'] for b in bills if b['kind']=='rent'),payroll_arrears=sum(b['unpaid'] for b in bills if b['kind']=='payroll'),credit=score,releases=len(releases),store=store)
    for i,event in enumerate(timeline['events']):
        c = int(event['cycle']); productive=event['productive']; kind=event['kind']; direct=int(event['direct']); earned=int(event['earned']); settled=int(event['settled'])
        if kind == 'release':
            releases.append(dict(game=event['release'],cycle=c,review=event['review'],scope=event['scope']))
            checkpoints[str(c)]=snap(); continue
        if kind == 'hire': direct -= scenario['fee']*100
        if kind == 'course': direct -= scenario['tuition']*100
        if cash+direct < 0:
            stop=dict(reason='direct_unaffordable',cycle=c,event=i,kind=kind,cash=cash,needed=-direct); break
        due=[]
        temp_hires=dict(hires); temp_courses=dict(courses)
        if kind == 'hire':
            temp_hires[event['employee']] = dict(cycle=c,productive=productive)
        if kind == 'course': temp_courses[event['employee']]=dict(cycle=c,productive=productive)
        if productive and c%2==0:
            due.append(bill('rent',c,50000,'studio'))
            for employee,h in temp_hires.items():
                first=due_after(h,due_rule)
                if c>=first and (c-first)%2==0:
                    wage=scenario['wage']
                    course=temp_courses.get(employee)
                    if course:
                        effective=course_due(course,scenario['raise_when'])
                        if c>=effective: wage+=scenario['raise']
                    due.append(bill('payroll',c,wage*100,employee))
        old_unpaid=sum(b['unpaid'] for b in bills)
        available=cash+direct+settled
        if old_unpaid and ((not productive and direct<0) or (productive and available<old_unpaid+sum(b['total'] for b in due))):
            stop=dict(reason='arrears_preflight',cycle=c,event=i,kind=kind,cash=cash); break
        hires=temp_hires; courses=temp_courses
        if 'native_cycle' in event: native_action_cycle=int(event['native_cycle'])
        cycle=c; cash+=direct+settled
        month=(c-1)//2+1 if productive else c//2+1
        row=row_for(month)
        row['direct']+=direct; row['earned']+=earned; row['settled']+=settled
        if kind not in ['financing_in','principal_paid']: row['operating_direct']+=direct
        totals['direct']+=direct; totals['earned']+=earned; totals['settled']+=settled
        bills.extend(due)
        for b in due: row[b['kind']+'_due']+=b['total']; totals[b['kind']+'_due']+=b['total']
        # Due-order assumption: older bills first; rent before payroll on a tie.
        for b in sorted(bills,key=lambda b:(b['due'],0 if b['kind']=='rent' else 1,str(b['source']))):
            if b['unpaid']:
                cash,payment=service(b,cash,c)
                row[b['kind']+'_paid']+=payment; totals[b['kind']+'_paid']+=payment
        row['profit']=row['earned']+row['operating_direct']-row['rent_due']-row['payroll_due']
        if productive and c%2==0:
            score,change=close_credit(score,bills,c,row['profit'])
            credit.append(dict(cycle=c,score=score,change=change,profit=row['profit']))
        low=min(low,cash)
        if kind=='store': store=True
        checkpoints[str(c)]=snap()
        if any(b['unpaid'] for b in bills):
            shortfall=dict(reason='bill_shortfall',cycle=c,event=i,kind=kind,cash=cash,**{k:v for k,v in snap().items() if k!='cash'})
            if first_shortfall is None: first_shortfall=shortfall
            # Before hiring, preserve the demonstrated native recovery route;
            # after hiring, censor at the first shortfall without inventing
            # an employee-driven recovery or adaptive income action.
            if hires: stop=shortfall; break
    final=snap()
    assert cash>=0 and cash == timeline['initial']+totals['direct']+totals['settled']-totals['rent_paid']-totals['payroll_paid']
    common={}
    for c in [12,14,18,24,36,48]:
        if c<=cycle and str(c) in checkpoints: common[str(c)]=checkpoints[str(c)]
    result=dict(scenario=scenario,final_cycle=cycle,low=low,final=final,stop=stop,first_shortfall=first_shortfall,releases=releases,totals=dict(totals),common=common,
                hires=list(hires.values()),first_dues=[due_after(h,due_rule) for h in hires.values()],courses=list(courses.values()))
    if detail: result.update(rows=list(rows.values()),bills=bills,credit_history=credit,checkpoints=checkpoints)
    return result

def scenario(**changes):
    s=dict(wage=0,fee=0,count=0,hire_point='start',hire_cycles=0,first='full',tuition=0,course_cycles=0,raise_when='next',course_point='hire')
    s['raise']=0; s.update(changes); return s

def key_for(s): return f"{s['count']}_{s['hire_point']}_{s['hire_cycles']}_{s['course_cycles']}_{s['course_point']}"

def compact_trace(value):
    if isinstance(value,list): return [compact_trace(v) for v in value]
    if not isinstance(value,dict): return value
    result={}
    for key,item in value.items():
        if key=='finance_report': continue
        if key=='finance' and isinstance(item,dict):
            result[key]=dict(cash_cents=item.get('cash_cents'),cycle=item.get('last_cycle'),credit=item.get('credit',{}).get('score'),unpaid_rent_cents=sum(b['unpaid_cents'] for b in item.get('obligations',[])))
        else: result[key]=compact_trace(item)
    return result

def main():
    engine=json.loads((ROOT/'timelines.json').read_text())
    assert not engine['failures'], engine['failures'][:5]
    finance_only='--finance-only' in sys.argv
    compact_native={}
    if finance_only:
        with gzip.open(HERE/'native-routes.jsonl.gz','rt',encoding='utf8') as f:
            for line in f:
                row=json.loads(line); compact_native[row['tag']]=row['route']
    validations=[]; native={}; reward={}; details={}; aggregates=defaultdict(Counter); failures=[]; total=0
    with gzip.open(HERE/'financial-arms.jsonl.gz','wt',encoding='utf8') as output:
        for tag,variants in sorted(engine['routes'].items()):
            route=compact_native[tag] if finance_only else json.loads((ROOT/'results'/f'{tag}.json').read_text())
            control=replay(variants['native'],scenario(),True)
            ledger=route['final']['finance']
            valid=(control['final']['cash']==ledger['cash_cents'] and control['final']['credit']==ledger['credit']['score'] and control['totals'].get('earned',0)==sum(r['sales_net_earned_cents'] for r in ledger['monthly_rows']) and control['totals'].get('settled',0)==sum(r['sales_settled_cents'] for r in ledger['monthly_rows']) and control['final']['rent_arrears']==sum(b['unpaid_cents'] for b in ledger['obligations']))
            rows_by_month={r['month']:r for r in control['rows']}
            monthly_exact=all(all(rows_by_month[r['month']][a]==r[b] for a,b in [('earned','sales_net_earned_cents'),('settled','sales_settled_cents'),('profit','net_profit_cents'),('rent_due','rent_due_cents'),('rent_paid','rent_paid_cents')]) for r in ledger['monthly_rows'])
            valid=valid and monthly_exact
            # The native route may legally recover after its first rent failure;
            # a censored payroll study compares only its accepted prefix.
            if control['stop']:
                snap=next((o['snapshot'] for o in route['finance_observations'] if o['cycle']==control['final_cycle']),None)
                valid=snap is not None and control['final']['cash']==snap['cash_cents'] and control['final']['credit']==snap['credit']['score']
            validations.append(dict(route=tag,valid=valid,monthly_exact=monthly_exact,censored=bool(control['stop'])))
            if not valid: failures.append(tag)
            native[tag]=dict(releases=route['releases'],stop=route['stop'],low=min([route['initial']['cash_cents']]+[a.get('after',{}).get('cash_cents',route['initial']['cash_cents']) for a in route['actions']]),final_cash=ledger['cash_cents'],final_cycle=ledger['last_cycle'],events=route['trial_events'],control=control)
            # Native no-hire paths cover all 32 startup/budget/choice controls.
            if route['reward']=='none':
                grid=itertools.product(WAGES,[0,100,200],[1,2,3],['start','release','studio'],[0,1],['crossed','full'])
                for wage,fee,count,point,cycles,first in grid:
                    s=scenario(wage=wage,fee=fee,count=count,hire_point=point,hire_cycles=cycles,first=first)
                    result=replay(variants[key_for(s)],s)
                    result['route']=tag; result['study']='payroll'; output.write(json.dumps(result,separators=(',',':'))+'\n'); total+=1
                    a=aggregates[f'payroll/{route["band"]}/{route["funding"]}/{wage}/{count}/{point}/{first}']
                    a['arms']+=1; a['completed']+=not result['stop']; a['game2']+=len(result['releases'])>=2; a['store']+=result['final']['store']
            if route['band'] in ['early','slow'] and (route['reward']=='none' or route['staff']==1):
                for wage,count,hc,tuition,cc,raise_amount,when,point,hire_point in itertools.product(WAGES,[1,2],[0,1],[0,75,150],[0,1],[0,25],['same','next'],['hire','game2'],['release','studio']):
                    s=scenario(wage=wage,fee=100,count=count,hire_point=hire_point,hire_cycles=hc,tuition=tuition,course_cycles=cc,raise_when=when,course_point=point)
                    s['raise']=raise_amount
                    result=replay(variants[key_for(s)],s)
                    result['route']=tag; result['study']='course'; output.write(json.dumps(result,separators=(',',':'))+'\n'); total+=1
                    a=aggregates[f'course/{route["reward"]}/{route["band"]}/{hire_point}/{wage}/{count}/{tuition}/{cc}/{raise_amount}/{when}/{point}']
                    a['arms']+=1; a['completed']+=not result['stop']; a['game2']+=len(result['releases'])>=2; a['store']+=result['final']['store']
            for count,wage,point in itertools.product([1,2,3],[10,50,75,100],['start','release','studio']):
                s=scenario(wage=wage,fee=100,count=count,hire_point=point,hire_cycles=1)
                details[f'{tag}/{count}/{wage}/{point}']=replay(variants[key_for(s)],s,True)
    assert not failures, failures
    (HERE/'finance-summary.json').write_text(json.dumps(dict(native_validation=validations,native_earning_checks=engine['checks'],arms=total,aggregates=aggregates),indent=2))
    with gzip.open(HERE/'selected-finance-traces.json.gz','wt',encoding='utf8') as f: json.dump(details,f,separators=(',',':'))
    if finance_only:
        print('Financial arms:',total,'Native controls reconciled:',len(validations),'earning checks:',engine['checks'],flush=True)
        return
    # All decision traces are reproducible; compress originals instead of
    # copying hundreds of MB of repeated menus to shared engineering memory.
    index=[]
    with gzip.open(HERE/'native-routes.jsonl.gz','wt',encoding='utf8') as f:
        for path in sorted((ROOT/'results').glob('*.json')):
            if path.name=='route_base_middle_synergy_1104_bundle_1.json': continue # discarded pilot
            data=json.loads(path.read_text())
            compact=compact_trace(data)
            compact['final']['finance']=data['final']['finance'] # one authoritative full journal
            compact['finance_observations']=[dict(cycle=o['cycle'],cash_cents=o['snapshot']['cash_cents'],credit=o['snapshot']['credit']['score'],unpaid_rent_cents=sum(b['unpaid_cents'] for b in o['snapshot']['obligations'])) for o in data['finance_observations']]
            f.write(json.dumps(dict(tag=path.stem,route=compact),separators=(',',':'))+'\n')
            index.append(dict(tag=path.stem,sha256=hashlib.sha256(path.read_bytes()).hexdigest(),bytes=path.stat().st_size))
    (HERE/'evidence-index.json').write_text(json.dumps(index,indent=2))
    print('Financial arms:',total,'Native controls reconciled:',len(validations),'earning checks:',engine['checks'],flush=True)

if __name__=='__main__': main()
